"""add model user_images

Revision ID: 290178f9df82
Revises: 6f404ff1001d
Create Date: 2022-10-15 23:58:22.523753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290178f9df82'
down_revision = '6f404ff1001d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images_users')
    # ### end Alembic commands ###
