"""prueba

Revision ID: 438433d870c9
Revises: d4f9734a35bf
Create Date: 2022-10-14 01:07:48.494261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438433d870c9'
down_revision = 'd4f9734a35bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images_product', 'quantity')
    op.drop_column('images_product', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_product', sa.Column('price', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('images_product', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
