"""add status model images-product

Revision ID: 6f404ff1001d
Revises: 438433d870c9
Create Date: 2022-10-14 13:56:57.974509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f404ff1001d'
down_revision = '438433d870c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images_product', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images_product', 'status')
    # ### end Alembic commands ###
